[[language]]
name="rust"
formatter = { command = "rustfmt" , args = ["+nightly"] }

[[language]]
name = "markdown"
auto-format = true
formatter = {command = "prettier", args = ["--parser", "markdown", "--print-width", "80", "--prose-wrap", "always"]}

[[language]]
name = "bash"
auto-format = true
formatter = {command = "shfmt", args = ["--simplify", "--indent 2"]}
